# Generated by Django 4.2.19 on 2025-02-12 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zycwz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zy_name', models.CharField(max_length=20)),
                ('zy_profession', models.CharField(max_length=20)),
                ('zy_price', models.FloatField()),
                ('zy_work', models.FloatField()),
            ],
            options={
                'verbose_name': '中药信息',
                'db_table': 'zycwz',
            },
        ),
    ]
